# This workflow uses actions that are not certified by GitHub.
name: Flutter for Android

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 22

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Setup Flutter SDK
        uses: flutter-actions/setup-flutter@v2
        with:
          channel: stable
          version: 3.19.5

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze project source
        run: dart analyze

#      - name: Run tests
#        run: flutter test
